import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'dart:ui';
import 'package:google_fonts/google_fonts.dart';
import 'package:suellas/utils.dart';
import 'package:suellas/customer/rewards_screen.dart';
void main() {
  runApp(const Rewards());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Rewards extends StatelessWidget {
  const Rewards({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Rewards(),
        ]),
      ),
    );
  }
}

class Rewards extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 414,
          height: 896,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 414,
                  height: 896,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: -4,
                        top: -3,
                        child: Container(
                          width: 421,
                          height: 410,
                          decoration: BoxDecoration(color: Color(0xFF2F6E53)),
                        ),
                      ),
                      Positioned(
                        left: 18,
                        top: 40,
                        child: Container(
                          width: 362.73,
                          height: 42.57,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 325.33,
                                top: 16.77,
                                child: Container(
                                  width: 23.53,
                                  height: 10.97,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Opacity(
                                          opacity: 0.35,
                                          child: Container(
                                            width: 21.28,
                                            height: 10.97,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 0.50, color: Colors.white),
                                                borderRadius: BorderRadius.circular(2.67),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 1.93,
                                        top: 1.94,
                                        child: Container(
                                          width: 17.41,
                                          height: 7.10,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(1.33),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 305.66,
                                top: 16.77,
                                child: Container(
                                  width: 14.83,
                                  height: 10.64,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/15x11"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 284.38,
                                top: 17.09,
                                child: Container(
                                  width: 16.44,
                                  height: 10.32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/16x10"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20.31,
                                top: 6.77,
                                child: Container(
                                  width: 52.23,
                                  padding: const EdgeInsets.only(top: 5),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 52.23,
                                        child: Text(
                                          '9:41',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 15,
                                            fontFamily: 'Inter',
                                            fontWeight: FontWeight.w400,
                                            height: 1.33,
                                            letterSpacing: -0.24,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 82,
                        top: 210,
                        child: Container(
                          width: 250,
                          height: 152,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 224.66,
                        top: 227.91,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.32),
                          child: Container(
                            width: 72.94,
                            height: 147.31,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 19.76,
                                  top: 101.20,
                                  child: Container(
                                    width: 31.53,
                                    height: 35.65,
                                    child: Stack(children: [
                                    ,
                                    ]),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 105,
                        top: 219,
                        child: SizedBox(
                          width: 170,
                          height: 26,
                          child: Text(
                            'SUELLAS REWARD',
                            style: TextStyle(
                              color: Color(0xFF00613A),
                              fontSize: 11,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w700,
                              height: 1.82,
                              letterSpacing: 1.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 104,
                        top: 298,
                        child: Container(
                          width: 133,
                          height: 18.34,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 3,
                                top: 0,
                                child: Container(
                                  width: 130,
                                  height: 18,
                                  decoration: ShapeDecoration(
                                    color: Color(0xC9D7D7D7),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 0.25,
                                        color: Colors.black.withOpacity(0.03999999910593033),
                                      ),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 73.82,
                                  height: 18.34,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF57CC99),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 91,
                        top: 326,
                        child: SizedBox(
                          width: 143,
                          height: 27,
                          child: Text(
                            '65 Stars to Next Rewards',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF00613A),
                              fontSize: 9,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 2.22,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 105,
                        top: 257,
                        child: Container(
                          width: 90,
                          height: 26,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(
                                  width: 43,
                                  height: 26,
                                  child: Text(
                                    '35',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 26,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w700,
                                      height: 0.77,
                                      letterSpacing: 1,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 40,
                                top: 1,
                                child: Text(
                                  '/150',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 21,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w700,
                                    height: 0.95,
                                    letterSpacing: 1,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 257,
                        top: 245,
                        child: Container(
                          width: 36,
                          height: 36,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFCD581),
                            shape: StarBorder(
                              points: 5,
                              innerRadiusRatio: 0.38,
                              pointRounding: 0,
                              valleyRounding: 0,
                              rotation: 0,
                              squash: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 343,
                        top: 97,
                        child: Container(
                          width: 24,
                          height: 24,
                          padding: const EdgeInsets.only(
                            top: 3,
                            left: 2,
                            right: 2,
                            bottom: 3.22,
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 20,
                                height: 17.78,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/20x18"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 143,
                        top: 86,
                        child: Container(
                          width: 127,
                          height: 50,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/127x50"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 96,
                        child: Container(
                          width: 30,
                          height: 30,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  child: Stack(children: [
                                  ,
                                  ]),
                                ),
                              ),
                              Positioned(
                                left: 3,
                                top: 3,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  padding: const EdgeInsets.only(
                                    top: 1,
                                    left: 3,
                                    right: 2.50,
                                    bottom: 1.50,
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 18.50,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 18.50,
                                                height: 17.35,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 18.50,
                                                        height: 17.35,
                                                        decoration: BoxDecoration(
                                                          image: DecorationImage(
                                                            image: NetworkImage("https://via.placeholder.com/18x17"),
                                                            fit: BoxFit.fill,
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 169,
                        top: 168,
                        child: Text(
                          'Rewards',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 1.25,
                            letterSpacing: 1,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 47,
                        top: 569,
                        child: Container(
                          width: 320,
                          height: 82,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 54,
                                top: 23,
                                child: SizedBox(
                                  width: 261,
                                  child: Text(
                                    'Plus collect double stars on deep clean service',
                                    style: TextStyle(
                                      color: Colors.black.withOpacity(0.5699999928474426),
                                      fontSize: 12,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.67,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 55,
                                top: 62,
                                child: Text(
                                  'Valid: September 1 - 15, 2023',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 10,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 2,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  padding: const EdgeInsets.symmetric(horizontal: 3.33, vertical: 6.67),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 33.33,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 55,
                                top: 0,
                                child: Text(
                                  '10% Off on your 2nd Pair of Deep Clean',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 47,
                        top: 692,
                        child: Container(
                          width: 315,
                          height: 66,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 54,
                                top: 23,
                                child: SizedBox(
                                  width: 261,
                                  child: Text(
                                    'Open to SM Baguio and SM Urdaneta b',
                                    style: TextStyle(
                                      color: Colors.black.withOpacity(0.5699999928474426),
                                      fontSize: 12,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.67,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 55,
                                top: 46,
                                child: Text(
                                  'Valid: September 1 - 15, 2023',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 10,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 2,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  padding: const EdgeInsets.symmetric(horizontal: 3.33, vertical: 6.67),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 33.33,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 55,
                                top: 0,
                                child: Text(
                                  '5% Off on Shoe Restoration',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 47,
                        top: 798,
                        child: Container(
                          width: 315,
                          height: 66,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 54,
                                top: 23,
                                child: SizedBox(
                                  width: 261,
                                  child: Text(
                                    'Open to SM Baguio and SM Urdaneta b',
                                    style: TextStyle(
                                      color: Colors.black.withOpacity(0.5699999928474426),
                                      fontSize: 12,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.67,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 55,
                                top: 46,
                                child: Text(
                                  'Valid: September 1 - 15, 2023',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 10,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 2,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  padding: const EdgeInsets.symmetric(horizontal: 3.33, vertical: 6.67),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 33.33,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 55,
                                top: 0,
                                child: Text(
                                  '5% Off on Re-Glue',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 38,
                        top: 813,
                        child: Container(
                          width: 333,
                          height: 56,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 333,
                                  height: 56,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF0F0F3),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(30),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x7FAEAEC0),
                                        blurRadius: 20,
                                        offset: Offset(5, 5),
                                        spreadRadius: 0,
                                      )BoxShadow(
                                        color: Color(0xFFFFFFFF),
                                        blurRadius: 20,
                                        offset: Offset(-5, -5),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 30,
                                top: 16,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  padding: const EdgeInsets.only(
                                    top: 3.75,
                                    left: 2.75,
                                    right: 2.75,
                                    bottom: 3.58,
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 18.50,
                                        height: 16.67,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 88,
                                top: 16,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  padding: const EdgeInsets.symmetric(horizontal: 2, vertical: 3),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 20,
                                        height: 18,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 154,
                                top: 13,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  padding: const EdgeInsets.only(
                                    top: 4.19,
                                    left: 1.88,
                                    right: 1.88,
                                    bottom: 4.24,
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 26.25,
                                        height: 21.58,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 280,
                                top: 16,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  padding: const EdgeInsets.only(
                                    top: 2.81,
                                    left: 4.81,
                                    right: 4.85,
                                    bottom: 2.78,
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 14.34,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 221,
                                top: 16,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  padding: const EdgeInsets.symmetric(horizontal: 4.50, vertical: 3),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 15,
                                        height: 18,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 47,
                        top: 472,
                        child: Container(
                          width: 226,
                          height: 62,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 61,
                                top: 0,
                                child: Text(
                                  'Get 20% Off Basic Clean',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 61,
                                top: 23,
                                child: Text(
                                  'Open only to walk-ins',
                                  style: TextStyle(
                                    color: Colors.black.withOpacity(0.5699999928474426),
                                    fontSize: 12,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.67,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 61,
                                top: 42,
                                child: Text(
                                  'Valid: September 1 - 30, 2023',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 10,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 2,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  padding: const EdgeInsets.symmetric(horizontal: 3.33, vertical: 6.67),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 33.33,
                                        child: Stack(children: [
                                        ,
                                        ]),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 437,
                child: Text(
                  'Promotions',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}