workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Suellas
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.suellas.rewardstesting
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Clean workspace
        script: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Update CocoaPods
        script: |
          gem uninstall cocoapods -a --force
          gem install cocoapods -v 1.15.2
          pod setup --verbose

      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update --clean-install --verbose
          cd ..

      - name: Auto-versioning
        script: |
          VERSION_NAME="1.0.9"
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "com.suellas.rewardstesting" || echo 0)
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "BUILD_NUMBER=$NEW_BUILD" >> $CM_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $CM_ENV

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=$VERSION_NAME \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - dev-team@suellas.com
        notify:
          success: true
          failure: true
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - "Internal Testers"