workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Suellas
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.suellas.rewardstesting
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Nuclear CocoaPods Reset
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate
          rm -rf Podfile.lock Pods/ Flutter/Flutter.podspec
          cd ..
          gem uninstall cocoapods -a --force
          gem install cocoapods -v 1.15.2

      - name: Full Specs Update
        script: |
          pod repo remove trunk
          pod setup --verbose
          pod repo update --verbose

      - name: Generate Podfile
        script: |
          cd ios
          echo "source 'https://cdn.cocoapods.org/'" > Podfile
          echo "platform :ios, '13.0'" >> Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  use_frameworks!" >> Podfile
          echo "  use_modular_headers!" >> Podfile
          echo "  pod 'Firebase/Auth', '11.8.0'" >> Podfile
          echo "  pod 'FirebaseCore', '11.8.0'" >> Podfile
          cat ../.symlinks/plugins/*/ios/*.podspec | grep "pod '" >> Podfile
          cd ..

      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update --clean-install --verbose
          cd ..

      - name: Build IPA
        script: |
          flutter clean
          flutter build ipa --release \
            --build-name=1.0.9 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist \
            --verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - dev-team@suellas.com
        notify:
          success: true
          failure: true
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - "Internal Testers"