workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Suellas
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.suellas.rewardstesting
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
          
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Fetch latest TestFlight build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "com.suellas.rewardstesting" || echo 0)
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "Latest TestFlight Build Number: $LATEST_BUILD_NUMBER"
          echo "New Build Number: $NEW_BUILD_NUMBER"
          echo "BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $CM_ENV

      - name: Flutter clean (prevent caching issues)
        script: |
          flutter clean

      - name: Flutter build ipa with automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.7 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: false
