workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Suellas
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.suellas.rewardstesting
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
          flutter pub upgrade --major-versions
      - name: Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..
      - name: Flutter build ipa and automatic versioning
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "com.suellas.rewardstesting")
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))

          flutter build ipa --release \
            --build-name=1.1.1 \
            --build-number=$NEW_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: false
