workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Suellas
    triggering:
      events:
        - push
        - tag
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.suellas.rewardstesting
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Get latest build number from App Store Connect
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "com.suellas.rewardstesting" || echo 0)
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "New build number: $NEW_BUILD_NUMBER"
          echo "BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $CM_ENV
      - name: Flutter clean and build IPA
        script: |
          flutter clean
          flutter build ipa --release \
            --build-name=1.0.$NEW_BUILD_NUMBER \
            --build-number=$NEW_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: false

        triggering:
  events:
    - push:
        branches:
          - main  # or specify any branch you want to trigger the build for
    - tag
