// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMlIGKQ5GVxUHqU-Y736CKcP1dmi6rGFg',
    appId: '1:851718991062:web:48584def3843d5e58e6d77',
    messagingSenderId: '851718991062',
    projectId: 'suellas-867dd',
    authDomain: 'suellas-867dd.firebaseapp.com',
    storageBucket: 'suellas-867dd.appspot.com',
    measurementId: 'G-KX4CRW1PCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Hdi0chkSgDQJDsoWmOLo3Ikj64UP8_0',
    appId: '1:851718991062:android:719665a09160a0718e6d77',
    messagingSenderId: '851718991062',
    projectId: 'suellas-867dd',
    storageBucket: 'suellas-867dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcsVFZLimhfH21AKu4Jk4wLSDU8QLjLRs',
    appId: '1:851718991062:ios:4429a5bec613446b8e6d77',
    messagingSenderId: '851718991062',
    projectId: 'suellas-867dd',
    storageBucket: 'suellas-867dd.appspot.com',
    iosClientId: '851718991062-57d4hso6ua2tavafe8daovtssjud7lt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.suellas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcsVFZLimhfH21AKu4Jk4wLSDU8QLjLRs',
    appId: '1:851718991062:ios:4429a5bec613446b8e6d77',
    messagingSenderId: '851718991062',
    projectId: 'suellas-867dd',
    storageBucket: 'suellas-867dd.appspot.com',
    iosClientId: '851718991062-57d4hso6ua2tavafe8daovtssjud7lt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.suellas',
  );
}
